{application,delivery_simulator,
             [{description,"Logistics Simulator"},
              {vsn,"1.0.0"},
              {registered,[]},
              {applications,[kernel,stdlib,wx]},
              {env,[]},
              {modules,[control_center,dashboard_server,
                        delivery_simulator_app,delivery_simulator_sup,
                        map_data_100,map_data_200,visualization_server,
                        zone_manager]}]}.
